// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEXeu3-DJu6lJxTtUCqZ_E9O560gXaOQ',
    appId: '1:391070804204:web:cfc9a1648ac879ab13ddc9',
    messagingSenderId: '391070804204',
    projectId: 'digital-manual-2024',
    authDomain: 'digital-manual-2024.firebaseapp.com',
    storageBucket: 'digital-manual-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwFf6CFOeBxC33PEzvxWDeKaL4zr79eQ',
    appId: '1:391070804204:android:1485da27ef4cfc5513ddc9',
    messagingSenderId: '391070804204',
    projectId: 'digital-manual-2024',
    storageBucket: 'digital-manual-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5VDZ2jjFr3ag2BBI4ocGvJNVs2jYCEF4',
    appId: '1:391070804204:ios:89c0c20123a33f6713ddc9',
    messagingSenderId: '391070804204',
    projectId: 'digital-manual-2024',
    storageBucket: 'digital-manual-2024.appspot.com',
    iosBundleId: 'com.example.digitalManual',
  );

}